image: php:7.2

pipelines:
  default:
    - step: # Modify the commands below to build your repository
        script:
          - apt-get update && apt-get install -y unzip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer -V
          - php -r "file_exists('.env') || copy('.env.example', '.env');"
          - composer install
          - php artisan key:generate

image: node:8

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm run production
          - git init
          - git remote add production ssh://rapulu@34.70.80.109/home/rapulu/deploy.git
          - git push production master
